### ISSUE TITLE
Pages are missing their white background

### ISSUE THREAD

**Issue by jbd7** [iCaspar/arras#15]
I don't know if that change was intended, but I think it looks better in the previous Arras.
Unlike Posts, text in Pages in Arras3b1 is not against a white background, and have 1 frame less.

Example:
Page: http://arrastheme.net/support/
Post: http://arrastheme.net/arras-3-0-beta-is-up/

**Comment by jbd7** [comment]
White background restored for posts and pages in Arras 3.0.1

White background still missing on the "news" (latest post) section of the homepage.

**Comment by iCaspar** [comment]
Moving this to a new issue for the home page.

**Comment by jbd7** [comment]
Hi,

Is it by design that the border between the white background and grey one is not the same on the left and on the right, on pages?

![arras3-page-borders](https://cloud.githubusercontent.com/assets/13196991/12727858/8fc76a70-c927-11e5-94ff-bc2e64fd2cd5.png)
