### ISSUE TITLE
[improvement] Add "if ( ! function_exists" to functions, so that the theme can accept child themes

### ISSUE THREAD

**Issue by jbd7** [iCaspar/arras#27]
Hi Caspar,

When looking at modifying  `function arras_postfooter()` and `function arras_postheader()`, I realized that it would be much easier to override them with a function in the functions.php of my child theme is the original functions were first checking if the function already exists.

I don't know if you planned a way to easily override original functions. It seems that a good practice in wordpress theme development is to place this condition at the beginning of each function.

**Comment by iCaspar** [comment]
For a while, making functions "pluggable" was considered a best practice, but no longer.

Instead, both of those functions allow child themes to override them by allowing their output to be filtered, so you can in your child theme's `functions.php`:

    add_filter( 'arras_postheader', 'child_header_function' );
    add_filter( 'arras_postfooter', 'child_footer_function' );

    function child_header_function( $arras_header ) {
       // code to modify or completely replace header
      return $new_header;
    }

    function child_footer_function( $arras_footer ) {
      // code to modify or completely replace footer
      return $new_footer;
    }

**Comment by jbd7** [comment]
Hi Caspar,
Thanks. I had figured it out.
I made some amendements to my child theme to remove some 3.0.3 flaws, and I'm quite happy with the result. Let me know if you're picking up the theme again.
jb
