### ISSUE TITLE
changing photos for slideshow on homepage arras theme 1.3.5

### ISSUE THREAD

**Issue by jose1212** [iCaspar/arras#31]
I’ve been trying to change the pictures for the slideshow on the homepage. I tried going to the posts and I see that the words are there but not the pictures I see behind the words. Can someone help out?

arras theme 1.3.5 slideshow photo change

**Comment by iCaspar** [comment]
Arras 1.x pulls the slide pictures from either the post's featured image or, if the post doesn't have a featured image, the first image inserted into the post content. So you're probably looking for the featured image -- usually in the right sidebar of your post edit screen.
