### ISSUE TITLE
No "older entries" button

### ISSUE THREAD

**Issue by psycholyzern** [iCaspar/arras#32]
I have tried activating featured posts and news, but there is no older entries button. It will only show maximum of post I set and that is all,. People cant see older entries because there is no button for that.
 I'm using php7 if that matter.

Also, did you already started to work on Arras back?  Because I saw recent commits. Arras was my last wordpress theme a few years ago before I quit blogging. Now I wanna start again with Arras.

**Comment by psycholyzern** [comment]
Tested with php 5.6 and still no pagination.

**Comment by psycholyzern** [comment]
Seems that this theme is broken on my wordpress. Whatever customization I did, it wont update the theme. Now I got a lot of this error
```
PHP message: PHP Warning:  in_array() expects parameter 2 to be array, string given in /home/user/site/wp-content/themes/arras/library/customizer.php on line 49
```

I don't know how to remove the theme completely along with its settings in the database, so I guess goodbye Arras. Until there are solutions to this other than reinstall my worspress and start fresh, I had to use another theme for the time being.

**Comment by iCaspar** [comment]
Hey Psy,

The php version shouldn't make any difference with Arras 1.x versions.

As I recall, Arras 1.x versions relied on another plugin [WPPageNavi](https://wordpress.org/plugins/wp-pagenavi/) for pagination. I'm not sure that the current version will work with your older version of Arras, but it might be worth a try.

If you're looking to start over with a clean theme re-install and you have FTP and access to your site's database, here's how remove Arras:

1. FTP into your WordPress directory, then go to wp-content/themes/ and delete the arras directory you'll find there. That will remove the theme files.
2. Then to remove the Arras database settings, access your database (using an app such as phpMyAdmin that comes with many cPanel based hosting services, or Sequel Pro). Go into your WordPress database wp_options table (the 'wp_' part may be different depending on your install) and filter for 'arras-options' and 'arras_options'. Then delete those rows.

Done! Arras is gone from your WordPress install. Then you can reinstall fresh from there if you wish.

The problem with Arras as things currently stand, is that all of the current versions have some problems. I started working on it when, around WordPress version 3.6, the homepage slider broke down and, [Melvin Lee](https://github.com/zyml), Arras's original developer, had left off updating the theme. I took it as far as v1.6 (which resolved the homepage slider and pagination plugin issues), but there were still some significant issues. Melvin Lee had started on Arras 2.0 as well, but it seems that version never really got off the ground. I started on Version 3.0, but translating the extensive options into the (then new) WP Customizer didn't go as well as I'd hoped. So while v.3.0 has better responsive capabilities for mobile screens, it's customizer options functions leave a lot to be desired.

As you noticed, I recently started fiddling around with Arras again after a time away from it, and yes, there have been a few commits to the development branch here. I wish I could say that Arras 4.0 was forthcoming, but at this early stage, I simply cannot make any promises.

**Comment by psycholyzern** [comment]
Arras 4.0? A very good news! Take your time as you need :)

I deleted arras options from wp_options and Arras seems to freeze. Whatever I did to the customizer settings, it wont reflect on the theme. The slider, featured, news, widget, were still there even I disabled them. 
  What I ended up doing was reseting my wp_options. That fixed it! Also WPPageNavi is working great! Pagination is shown up again right now. Thanks a lot, now Im back on Arras :)
Will keep updating with any Arras 4.0 news. Thanks a lot for your work.
