### ISSUE TITLE
Arras Theme in Blogger

### ISSUE THREAD

**Issue by mabelgames** [iCaspar/arras#60]
Hi Caspar, 
I've been using Arras in Wordpress for over 10 years. Thanks for the lovely theme. Recently I would like to use this in Blogger too. Is Arras theme able to be used in Blogger? Pls advise if there is any downloadable file I can use. Thanks so much.

**Comment by iCaspar** [comment]
Sorry, I don't know of any adaptations of Arras for other blogging platforms.
